// @generated by protoc-gen-es v2.6.3 with parameter "target=js+dts,import_extension=.js"
// @generated from file dsl/cli.proto (package stately.cli, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_errors_error_details } from "../errors/error_details_pb.js";
import { file_migration } from "../migration_pb.js";
import { file_package } from "../package_pb.js";

/**
 * Describes the file dsl/cli.proto.
 */
export const file_dsl_cli =
  /*@__PURE__*/
  fileDesc(
    "Cg1kc2wvY2xpLnByb3RvEgtzdGF0ZWx5LmNsaSLOAQoLRFNMUmVzcG9uc2USMwoHcGFja2FnZRgFIAEoCzIiLnN0YXRlbHkuc2NoZW1hbW9kZWwuU2NoZW1hUGFja2FnZRIyCgptaWdyYXRpb25zGAIgAygLMh4uc3RhdGVseS5zY2hlbWFtb2RlbC5NaWdyYXRpb24SMwoGZXJyb3JzGAMgAygLMiMuc3RhdGVseS5lcnJvcnMuU3RhdGVseUVycm9yRGV0YWlscxIbCgtkc2xfdmVyc2lvbhgEIAEoCUIGukgDyAEBSgQIARACQmgKD2NvbS5zdGF0ZWx5LmNsaUIIQ2xpUHJvdG9QAaICA1NDWKoCC1N0YXRlbHkuQ2xpygILU3RhdGVseVxDbGniAhdTdGF0ZWx5XENsaVxHUEJNZXRhZGF0YeoCDFN0YXRlbHk6OkNsaWIGcHJvdG8z",
    [file_errors_error_details, file_migration, file_package],
  );

/**
 * Describes the message stately.cli.DSLResponse.
 * Use `create(DSLResponseSchema)` to create a new message.
 */
export const DSLResponseSchema = /*@__PURE__*/ messageDesc(file_dsl_cli, 0);
