// @generated by protoc-gen-es v2.2.4 with parameter "target=js+dts,import_extension=.js"
// @generated from file dsl/cli.proto (package stately.cli, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../buf/validate/validate_pb.js";
import { file_errors_error_details } from "../errors/error_details_pb.js";
import { file_migration } from "../migration_pb.js";

/**
 * Describes the file dsl/cli.proto.
 */
export const file_dsl_cli =
  /*@__PURE__*/
  fileDesc(
    "Cg1kc2wvY2xpLnByb3RvEgtzdGF0ZWx5LmNsaSLaAQoLRFNMUmVzcG9uc2USRQoPZmlsZV9kZXNjcmlwdG9yGAEgASgLMiQuZ29vZ2xlLnByb3RvYnVmLkZpbGVEZXNjcmlwdG9yUHJvdG9CBrpIA8gBARIyCgptaWdyYXRpb25zGAIgAygLMh4uc3RhdGVseS5zY2hlbWFtb2RlbC5NaWdyYXRpb24SMwoGZXJyb3JzGAMgAygLMiMuc3RhdGVseS5lcnJvcnMuU3RhdGVseUVycm9yRGV0YWlscxIbCgtkc2xfdmVyc2lvbhgEIAEoCUIGukgDyAEBQmgKD2NvbS5zdGF0ZWx5LmNsaUIIQ2xpUHJvdG9QAaICA1NDWKoCC1N0YXRlbHkuQ2xpygILU3RhdGVseVxDbGniAhdTdGF0ZWx5XENsaVxHUEJNZXRhZGF0YeoCDFN0YXRlbHk6OkNsaWIGcHJvdG8z",
    [
      file_buf_validate_validate,
      file_errors_error_details,
      file_google_protobuf_descriptor,
      file_migration,
    ],
  );

/**
 * Describes the message stately.cli.DSLResponse.
 * Use `create(DSLResponseSchema)` to create a new message.
 */
export const DSLResponseSchema = /*@__PURE__*/ messageDesc(file_dsl_cli, 0);
