// @generated by protoc-gen-es v2.2.4 with parameter "target=js+dts,import_extension=.js"
// @generated from file extensions.proto (package stately.schemamodel, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv1";
import type { FieldOptions, MessageOptions } from "@bufbuild/protobuf/wkt";
import type {
  FieldOptions as FieldOptions$1,
  MessageOptions as MessageOptions$1,
} from "./options_pb.js";

/**
 * Describes the file extensions.proto.
 */
export declare const file_extensions: GenFile;

/**
 * @generated from extension: optional stately.schemamodel.MessageOptions message = 169355;
 */
export declare const message: GenExtension<MessageOptions, MessageOptions$1>;

/**
 * @generated from extension: optional stately.schemamodel.FieldOptions field = 169355;
 */
export declare const field: GenExtension<FieldOptions, FieldOptions$1>;
