// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file extensions.proto (package stately.schemamodel, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FieldOptions, MessageOptions, proto3 } from "@bufbuild/protobuf";
import {
  FieldOptions as FieldOptions$1,
  MessageOptions as MessageOptions$1,
} from "./options_pb.js";

/**
 * @generated from extension: optional stately.schemamodel.MessageOptions message = 169355;
 */
export const message = proto3.makeExtension("stately.schemamodel.message", MessageOptions, () => ({
  no: 169355,
  kind: "message",
  T: MessageOptions$1,
  opt: true,
}));

/**
 * @generated from extension: optional stately.schemamodel.FieldOptions field = 169355;
 */
export const field = proto3.makeExtension("stately.schemamodel.field", FieldOptions, () => ({
  no: 169355,
  kind: "message",
  T: FieldOptions$1,
  opt: true,
}));
