// @generated by protoc-gen-es v1.10.0 with parameter "target=js+dts"
// @generated from file extensions.proto (package stately.schemamodel, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { Extension, FieldOptions, MessageOptions } from "@bufbuild/protobuf";
import type {
  FieldOptions as FieldOptions$1,
  MessageOptions as MessageOptions$1,
} from "./options_pb.js";

/**
 * @generated from extension: optional stately.schemamodel.MessageOptions message = 169355;
 */
export declare const message: Extension<MessageOptions, MessageOptions$1>;

/**
 * @generated from extension: optional stately.schemamodel.FieldOptions field = 169355;
 */
export declare const field: Extension<FieldOptions, FieldOptions$1>;
