// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file extensions.proto (package stately.schemamodel, syntax proto3)
/* eslint-disable */

import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import { file_options } from "./options_pb.js";

/**
 * Describes the file extensions.proto.
 */
export const file_extensions =
  /*@__PURE__*/
  fileDesc(
    "ChBleHRlbnNpb25zLnByb3RvEhNzdGF0ZWx5LnNjaGVtYW1vZGVsOmMKB21lc3NhZ2USHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9wdGlvbnMYi6sKIAEoCzIjLnN0YXRlbHkuc2NoZW1hbW9kZWwuTWVzc2FnZU9wdGlvbnNSB21lc3NhZ2WIAQE6WwoFZmllbGQSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGIurCiABKAsyIS5zdGF0ZWx5LnNjaGVtYW1vZGVsLkZpZWxkT3B0aW9uc1IFZmllbGSIAQFClwEKF2NvbS5zdGF0ZWx5LnNjaGVtYW1vZGVsQg9FeHRlbnNpb25zUHJvdG9QAaICA1NTWKoCE1N0YXRlbHkuU2NoZW1hbW9kZWzKAhNTdGF0ZWx5XFNjaGVtYW1vZGVs4gIfU3RhdGVseVxTY2hlbWFtb2RlbFxHUEJNZXRhZGF0YeoCFFN0YXRlbHk6OlNjaGVtYW1vZGVsYgZwcm90bzM",
    [file_google_protobuf_descriptor, file_options],
  );

/**
 * @generated from extension: optional stately.schemamodel.MessageOptions message = 169355;
 */
export const message = /*@__PURE__*/ extDesc(file_extensions, 0);

/**
 * @generated from extension: optional stately.schemamodel.FieldOptions field = 169355;
 */
export const field = /*@__PURE__*/ extDesc(file_extensions, 1);
